import { useRouter } from 'next/router'
import { useContext, useEffect,useState } from 'react'
import Head from 'next/head'
import Layout from '../components/Layout.jsx'
import UserContext from '../components/UserContext'
import { useTheme } from "next-themes"
import { useSupabaseClient } from "@supabase/auth-helpers-react"

export default function Contact() {
  const supabase = useSupabaseClient()
  const { user, logout, loading } = useContext(UserContext)
  const router = useRouter()
  //const r = document.querySelector(':root')
  //const rs = getComputedStyle(document.documentElement).getPropertyValue('--bleu')
  const [colour,setColor] = useState()
  

  const setColour = async () =>{
    const {data,error} = await supabase
    .from('profiles')
    .select('color')
    .eq('id',user?.id)
    .limit(1)
    .single()
    console.log(data?.color)
    
    if(user){
      const color = getComputedStyle(document.documentElement).getPropertyValue('--bleu')
      console.log(`--bleu: ${color}`);
      setColor(data?.color)
}

  }

  useEffect(() => {
    setColor(getComputedStyle(document.documentElement).getPropertyValue('--bleu'))
    
  }, [user])


  const {systemTheme,theme,setTheme} = useTheme()
  const renderThemeChanger =() =>{
    const currentTheme = theme === 'system' ? systemTheme:theme

    if(currentTheme == 'dark'){
      return <><input value='Light' type="button" className="inline-block rounded-lg px-4 py-1.5 text-base font-semibold leading-7 text-gray-900 ring-2 ring-gray-900/10 hover:ring-gray-900/30 dark:bg-gray-800 dark:text-gray-100"  onClick={() => setTheme('light')}/><br/>
       </>
       //
    }else{
      return <><input type="color"
               value={colour}
               id="color" onChange={e => { setColor(e.currentTarget.value)}}/><br/>
               <input type='button' className ='bg-bleu hover:bg-gray-700 content-between text-white font-bold py-2 px-4 rounded' value='Save' onClick={saveColor}/></>    }
       //
  }

  const saveColor = async () =>{
    const {error} = await supabase
    .from('profiles')
    .update({color:colour.toString()})
    .eq('id',user.id)
    router.reload()
  }



// r.style.setProperty('--bleu', color)
 


  
  useEffect(() => {
    if (!(user || loading)) {
      router.push('/login')
    }
  }, [user, loading, router])
  
  const onClickLogout = function() {
    document.documentElement.style.setProperty('--bleu', '#5952CA');
    logout()
  }


  
  return (
    <Layout>
      <Head>
        <title>WebTech - user signedin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { !(user || loading) ?
        <p>Redirecting...</p>
        :
        <>
          <button
            className="rounded px-3 py-2 text-white bg-slate-500 hover:bg-blue-500"
            onClick={onClickLogout}
          >
            Logout
          </button>

          <br/>
        Select a color
        <br/>
        {renderThemeChanger()}

          <pre><code>{JSON.stringify(user, null, 2)}</code></pre>
        </>
      }
    </Layout>
  )
}